### ISSUE TITLE
Sparse array support?

### ISSUE THREAD

**Issue by Zaseth** [neoxic/lua-amf3#10]
Hey there!

I've been scattering around to look for an AMF3 library and I find this one interesting. Does your library support these kind of arrays down below? I believe they're sparse arrays or something, it's an array that kind of looks like an object.

```actionscript
var content:Array = [];

content['!Logon'] = [];
content['!movieID'] = '123';
content['!userID'] = '456';

// writeObject(content);
```

Thank you for your work!

**Comment by neoxic** [comment]
Hello! Thanks for your interest!

This module is for Lua, so in order to properly understand and reply to your question, a Lua code snippet is required (your example seems to be JScript if I am not mistaken).

**Comment by neoxic** [comment]
Or you could provide an AMF3 binary dump, so I could tell what it will boil down to in Lua.

Generally, all inbound types are supported.

**Comment by Zaseth** [comment]
The code snippet is actionscript, it's basically ecmascript. I believe in the AMF3 docs there's a note about dense, sparse and associative arrays, but I guess you support it.

**Comment by neoxic** [comment]
Oh, right, ECMAScript... Now I see what kind of arrays you are talking about. Yes, these arrays (I call them associative or mixed) are fully supported inbound. But there's no way to have them outbound since the Object type is preferred (it is structurally the same for untyped associative data). As far as I can see, it shouldn't be a problem in ECMAScript since objects can be easily accessed as arrays. Please correct me if I'm wrong. In other words, why do you prefer arrays over anonymous objects?

**Comment by Zaseth** [comment]
I'm going to emulate a flash game and it uses this kind of array once to login. I know, it makes no sense whatsoever to use a mixed array like this, but there's basically nothing I can do about it. I need to be able to deserialize them.

**Comment by neoxic** [comment]
Yes, you should be able to do that right away.

**Comment by Zaseth** [comment]
Thanks!
